### ISSUE TITLE
GitHub Rate Limiting

### ISSUE THREAD

**Issue by jakirkham** [regro/circle_worker#3]
Looks like this is getting rate limited by GitHub.

```
2019-02-28 18:21:31,395 CRITICAL conda_forge_tick.make_graph || GITHUB ERROR ON FEEDSTOCK: fs.sshfs
403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.
<Response [403]>
```

ref: https://circleci.com/gh/regro/circle_worker/5852

**Comment by CJ-Wright** [comment]
Yep, when we try to post something (eg make a PR or close a PR, etc.) too many times we get hit with that.
This is a different limit than the standard 5000 per hour limit. It would be great if we had a retry mechanism for this.

**Comment by jakirkham** [comment]
Right. So this is some sort of frequency issue. What about doing a small sleep between PRs?

**Comment by CJ-Wright** [comment]
This isn't on the PR side, this is on the ``bot-rerun`` side. The PRs are slow enough to not hit this (rerendering takes time).

**Comment by mariusvniekerk** [comment]
Yeah, the more ideal approach would be to run the section that updates the pr_json independently of the main worker.  That way we can run that thing every 10 minutes or so.

**Comment by beckermr** [comment]
this is done. closing.
